### ISSUE TITLE
Support for newer versions?

### ISSUE THREAD

**Issue by furicle** [CollaboraOnline/ADMX#21]
Am I correct in assuming this will not support LO 5.4 or 6.0 ?

**Comment by timar** [comment]
Most of the settings work with LO 5.4 and 6.0.

**Comment by Faeringen** [comment]
I have a wierd issue with the macro trusted location setting.
If we include $(temp) it will work if the users %temp% folder is "correctly" reflected like this:
"C:\Users\TEST-1\AppData\Local\Temp\23>"

But if the username is longer windows stuffs a ~ in the path and the macro location isn't trusted anymore.
"C:\Users\TEST-H~1\AppData\Local\Temp\13>"

Any suggestions?
