### ISSUE TITLE
Macro trusted location and temp folder

### ISSUE THREAD

**Issue by Faeringen** [CollaboraOnline/ADMX#24]
I have a wierd issue with the macro trusted location setting.
If we include $(temp) it will work if the users %temp% folder is "correctly" reflected like this:
"C:\Users\TEST-1\AppData\Local\Temp\23>"

But if the username is longer windows stuffs a ~ in the path and the macro location isn't trusted anymore.
"C:\Users\TEST-H~1\AppData\Local\Temp\13>"

Any suggestions?

**Comment by timar** [comment]
Could you please report this at https://bugs.documentfoundation.org ?
I don't think it's a bug in the ADMX template, rather a bug in LibreOffce itself.
